import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Clock3, LogIn, LogOut, RefreshCw } from "lucide-react";
import { ApiError } from "../api/httpClient";
import { checkIn, checkOut, getCurrentShift, getMyShifts, getShiftReport, type ShiftDto, type ShiftReportResponse } from "../api/shiftApi";

const dateValue = (offset = 0) => { const value = new Date(); value.setDate(value.getDate() + offset); return value.toISOString().slice(0, 10); };
const asIso = (value: string) => value ? new Date(`${value}T00:00:00`).toISOString() : undefined;

export default function ShiftManagementPage() {
  const [current, setCurrent] = useState<ShiftDto | null>(null); const [history, setHistory] = useState<ShiftDto[]>([]); const [report, setReport] = useState<ShiftReportResponse | null>(null); const [from, setFrom] = useState(dateValue(-30)); const [to, setTo] = useState(dateValue()); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function load() { setLoading(true); setError(""); try { const range = { from: asIso(from), to: asIso(to) }; const [mine, shiftReport] = await Promise.all([getMyShifts(range), getShiftReport(range)]); setHistory(mine); setReport(shiftReport); try { setCurrent(await getCurrentShift()); } catch { setCurrent(null); } } catch (err) { setError(err instanceof Error ? err.message : "Could not load shifts."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function changeShift(action: "in" | "out") { setWorking(true); setError(""); try { const result = action === "in" ? await checkIn() : await checkOut(); setCurrent(result.isOpen ? result : null); setSuccess(action === "in" ? "تم تسجيل بداية الدوام." : "تم تسجيل نهاية الدوام."); void load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not update shift."); } finally { setWorking(false); } }
  return <div dir="rtl" className="pos-page px-5 py-8"><main className="mx-auto max-w-7xl"><header className="pos-panel mb-6 flex flex-wrap items-center justify-between gap-4 p-6"><div className="flex items-center gap-3"><Link to="/dashboard" className="pos-icon-button" aria-label="Back"><ArrowRight size={20} /></Link><div><p className="pos-kicker">AL-ISRAA Supermarket</p><h1 className="text-2xl font-black text-white">إدارة الدوام</h1></div></div><Clock3 className="text-amber-400" size={30} /></header>{error && <p className="pos-error mb-5">{error}</p>}{success && <p className="pos-success mb-5">{success}</p>}
    <section className="pos-panel mb-6 flex flex-wrap items-center justify-between gap-4 p-6"><div><h2 className="font-bold text-white">{current ? "الدوام مفتوح" : "لا يوجد دوام مفتوح"}</h2><p className="mt-1 text-sm text-slate-300">{current ? `بدأ في ${formatDate(current.loginAt)}` : "ابدأ دوامك قبل تنفيذ عمليات البيع."}</p></div>{current ? <button disabled={working} onClick={() => void changeShift("out")} className="pos-danger"><LogOut size={18} /> تسجيل نهاية الدوام</button> : <button disabled={working} onClick={() => void changeShift("in")} className="pos-primary"><LogIn size={18} /> تسجيل بداية الدوام</button>}</section>
    <section className="pos-panel mb-6 p-6"><div className="flex flex-wrap items-end gap-3"><label className="pos-label">من<input className="pos-input" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="pos-label">إلى<input className="pos-input" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button onClick={() => void load()} className="pos-secondary"><RefreshCw size={16} /> تحديث التقرير</button></div>{report && <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["عدد الدوامات", report.totalShifts], ["إجمالي الدقائق", report.totalMinutes], ["عدد الفواتير", report.totalInvoices], ["إجمالي المبيعات", report.totalSales.toFixed(2)]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-amber-400/20 bg-black/20 p-4"><p className="text-xs text-slate-300">{label}</p><p className="mt-1 text-2xl font-black text-amber-400">{value}</p></div>)}</div>}</section>
    <section className="pos-panel p-6"><h2 className="mb-4 font-bold text-white">دواماتي</h2>{loading ? <p className="pos-muted">جارٍ التحميل...</p> : <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="border-b border-white/15 text-amber-300"><tr><th className="p-3">البداية</th><th className="p-3">النهاية</th><th className="p-3">المدة</th><th className="p-3">الفواتير</th><th className="p-3">المبيعات</th></tr></thead><tbody>{history.map((shift) => <tr key={shift.id} className="border-b border-white/10 text-slate-200"><td className="p-3">{formatDate(shift.loginAt)}</td><td className="p-3">{shift.logoutAt ? formatDate(shift.logoutAt) : "مفتوح"}</td><td className="p-3">{shift.durationMinutes} دقيقة</td><td className="p-3">{shift.invoiceCount}</td><td className="p-3">{shift.salesTotal.toFixed(2)}</td></tr>)}</tbody></table></div>}</section>
  </main></div>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("ar", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
