import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, KeyRound, Power, RefreshCw, UserCog, UserPlus } from "lucide-react";
import { ApiError } from "../api/httpClient";
import { activateUser, createUser, deactivateUser, getPermissions, getUserById, getUsers, setUserPermissions, updateUser, type PermissionDto, type UserDto } from "../api/userApi";

const blank = { fullName: "", username: "", password: "", role: "Cashier", permissionIds: [] as number[] };

// صلاحيات إلزامية لكل دور — نفس القائمة اللي بالباك اند (RolePermissions.MandatoryByRole).
// الريتيرن وتعديل السعر (Price Override) جزء أساسي من شغل الكاشير اليومي،
// مش خيار إداري ممكن ينسى يفعّله.
const MANDATORY_BY_ROLE: Record<string, string[]> = { Cashier: ["process_return", "edit_price"] };

function mandatoryIdsForRole(role: string, permissions: PermissionDto[]): number[] {
  const names = MANDATORY_BY_ROLE[role] ?? [];
  return permissions.filter((p) => names.includes(p.name ?? "")).map((p) => p.id);
}

export default function UserManagementPage() {
  const [users, setUsers] = useState<UserDto[]>([]); const [permissions, setPermissions] = useState<PermissionDto[]>([]);
  const [editing, setEditing] = useState<UserDto | null>(null); const [form, setForm] = useState(blank);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function load() { setLoading(true); try { const [allUsers, allPermissions] = await Promise.all([getUsers(), getPermissions()]); setUsers(allUsers); setPermissions(allPermissions); } catch (err) { setError(err instanceof Error ? err.message : "Could not load users."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  // كل ما يتغيّر الدور (أو تحمّل قائمة الصلاحيات لأول مرة)، الصلاحيات الإلزامية
  // للدور المختار بتنضاف تلقائياً — حتى الأدمن ما يحتاج يفتكر يحطها يدوياً،
  // والباك اند بيرضمها برضو حتى لو حدا حاول يتلاعب بالـ request مباشرة.
  useEffect(() => { const mandatory = mandatoryIdsForRole(form.role, permissions); if (mandatory.length === 0) return; setForm((current) => { const missing = mandatory.filter((id) => !current.permissionIds.includes(id)); if (missing.length === 0) return current; return { ...current, permissionIds: [...current.permissionIds, ...missing] }; }); }, [form.role, permissions]);
  function reset() { setEditing(null); setForm(blank); setError(""); }
  function togglePermission(id: number) { const mandatory = mandatoryIdsForRole(form.role, permissions); if (mandatory.includes(id)) return; setForm((current) => ({ ...current, permissionIds: current.permissionIds.includes(id) ? current.permissionIds.filter((item) => item !== id) : [...current.permissionIds, id] })); }
  async function startEdit(id: number) { setError(""); try { const user = await getUserById(id); setEditing(user); const assigned = permissions.filter((permission) => user.permissions?.includes(permission.name ?? "")).map((permission) => permission.id); setForm({ fullName: user.fullName ?? "", username: user.username ?? "", password: "", role: user.role ?? "Cashier", permissionIds: assigned }); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (err) { setError(err instanceof Error ? err.message : "Could not load user."); } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { if (editing) { await updateUser(editing.id, { fullName: form.fullName.trim(), username: form.username.trim(), role: form.role, newPassword: form.password.trim() || null }); if (form.role !== "Admin") await setUserPermissions(editing.id, form.permissionIds); setSuccess("User and permissions updated."); } else { await createUser({ fullName: form.fullName.trim(), username: form.username.trim(), password: form.password, role: form.role, permissionIds: form.permissionIds }); setSuccess("User created successfully."); } reset(); void load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not save user."); } finally { setSaving(false); } }
  async function changeStatus(user: UserDto) { try { if (user.isActive) await deactivateUser(user.id); else await activateUser(user.id); setSuccess(`User ${user.isActive ? "deactivated" : "activated"}.`); void load(); } catch (err) { setError(err instanceof Error ? err.message : "Could not update user."); } }
  return <div dir="rtl" className="pos-page px-5 py-8"><main className="mx-auto max-w-7xl"><header className="pos-panel mb-6 flex flex-wrap items-center justify-between gap-4 p-6"><div className="flex items-center gap-3"><Link to="/dashboard" className="pos-icon-button" aria-label="Back"><ArrowRight size={20} /></Link><div><p className="pos-kicker">AL-ISRAA Supermarket</p><h1 className="text-2xl font-black text-white">User and permissions management</h1></div></div><UserCog className="text-amber-400" size={30} /></header>
    {error && <p className="pos-error mb-5">{error}</p>}{success && <p className="pos-success mb-5">{success}</p>}
    <div className="grid gap-6 lg:grid-cols-[390px_1fr]"><section className="pos-panel h-fit p-6"><div className="mb-4 flex items-center gap-2 text-white">{editing ? <UserCog /> : <UserPlus />}<h2 className="font-bold">{editing ? "Edit user" : "New user"}</h2></div><form onSubmit={submit} className="space-y-3"><Field label="Full name" value={form.fullName} onChange={(value) => setForm({ ...form, fullName: value })} /><Field label="Username" value={form.username} onChange={(value) => setForm({ ...form, username: value })} /><Field label={editing ? "New password (optional)" : "Password"} type="password" required={!editing} value={form.password} onChange={(value) => setForm({ ...form, password: value })} /><label className="pos-label">Role<select className="pos-input" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option>Admin</option><option>Cashier</option><option>InventoryOnly</option></select></label><fieldset><legend className="pos-label mb-2">Permissions</legend><div className="max-h-44 space-y-2 overflow-y-auto rounded-xl border border-white/15 bg-black/20 p-3">{permissions.map((permission) => { const isMandatory = mandatoryIdsForRole(form.role, permissions).includes(permission.id); return <label key={permission.id} className={`flex gap-2 text-sm text-slate-200 ${isMandatory ? "cursor-not-allowed opacity-80" : "cursor-pointer"}`} title={isMandatory ? "Mandatory for this role — cannot be removed." : undefined}><input type="checkbox" checked={form.permissionIds.includes(permission.id)} disabled={isMandatory} onChange={() => togglePermission(permission.id)} /> <span>{permission.name}</span>{isMandatory && <span className="rounded-full bg-amber-500/20 px-2 py-0.5 text-[10px] font-bold text-amber-300">mandatory</span>}</label>; })}</div></fieldset><div className="flex gap-2"><button disabled={saving} className="pos-primary flex-1">{saving ? "Saving..." : editing ? "Save" : "Create"}</button>{editing && <button type="button" onClick={reset} className="pos-secondary">Cancel</button>}</div></form></section>
      <section className="pos-panel p-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-white">Users</h2><button onClick={() => void load()} className="pos-icon-button"><RefreshCw size={17} /></button></div>{loading ? <p className="pos-muted">Loading...</p> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-right text-sm"><thead className="border-b border-white/15 text-amber-300"><tr><th className="p-3">Name</th><th className="p-3">Role</th><th className="p-3">Status</th><th className="p-3">Permissions</th><th className="p-3" /></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b border-white/10 text-slate-200"><td className="p-3"><p className="font-semibold">{user.fullName}</p><p className="text-xs text-slate-400">{user.username}</p></td><td className="p-3">{user.role}</td><td className="p-3">{user.isActive ? "Active" : "Disabled"}</td><td className="max-w-52 p-3 text-xs text-slate-300">{user.permissions?.join(", ") || "—"}</td><td className="flex gap-2 p-3"><button onClick={() => void startEdit(user.id)} className="pos-table-button"><KeyRound size={15} /> Edit</button><button onClick={() => void changeStatus(user)} className="pos-danger"><Power size={15} /> {user.isActive ? "Disable" : "Enable"}</button></td></tr>)}</tbody></table></div>}</section></div>
  </main></div>;
}
function Field({ label, value, onChange, type = "text", required = true }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="pos-label">{label}<input className="pos-input" type={type} required={required} minLength={type === "password" ? 8 : undefined} autoComplete={type === "password" ? "new-password" : type === "text" ? "off" : undefined} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
